server:
  port: 8080

spring:
  datasource:
      url: jdbc:mysql://localhost:3306/student_management?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    # thymeleaf配置，开发环境不启用缓存，正式环境下请启用缓存，提高性能

# mybatis config
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
